### ISSUE TITLE
c3os-agent segfault on RPI4 

### ISSUE THREAD

**Issue by matclab** [c3os-io/c3os#19]
Here after is the journald log
```
Feb 03 12:01:47 monitor systemd[1]: c3os-agent.service: Scheduled restart job, restart counter is at 1.
Feb 03 12:01:47 monitor systemd[1]: Stopped c3os agent.
Feb 03 12:01:47 monitor systemd[1]: Started c3os agent.
Feb 03 12:01:47 monitor c3os[3034]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 03 12:01:47 monitor c3os[3034]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xb83bc4]
Feb 03 12:01:47 monitor c3os[3034]: goroutine 1 [running]:
Feb 03 12:01:47 monitor c3os[3034]: main.agent({0xf9042f, 0x15}, {0x40009018d8, 0x2, 0x2}, 0x0)
Feb 03 12:01:47 monitor c3os[3034]:         /work/cli/agent.go:42 +0x94
Feb 03 12:01:47 monitor c3os[3034]: main.main.func6(0x40002be160)
Feb 03 12:01:47 monitor c3os[3034]:         /work/cli/main.go:165 +0x10c
Feb 03 12:01:47 monitor c3os[3034]: github.com/urfave/cli.HandleAction({0xc4fde0, 0x1195e48}, 0x40002be160)
Feb 03 12:01:47 monitor c3os[3034]:         /go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xfc
Feb 03 12:01:47 monitor c3os[3034]: github.com/urfave/cli.Command.Run({{0xe3b142, 0x5}, {0x0, 0x0}, {0x4000936070, 0x1>
Feb 03 12:01:47 monitor c3os[3034]:         /go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x5fc
Feb 03 12:01:47 monitor c3os[3034]: github.com/urfave/cli.(*App).Run(0x400025a000, {0x40000b2000, 0x2, 0x2})
Feb 03 12:01:47 monitor c3os[3034]:         /go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x618
Feb 03 12:01:47 monitor c3os[3034]: main.main()
Feb 03 12:01:47 monitor c3os[3034]:         /work/cli/main.go:338 +0x1458
Feb 03 12:01:47 monitor systemd[1]: c3os-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 03 12:01:47 monitor systemd[1]: c3os-agent.service: Failed with result 'exit-code'.
```

**Comment by mudler** [comment]
Hi! thanks for the feedback, indeed looks like it stops there if there is `c3os` config found, but it should rather stop. 

I will fix this soon, as a heads up if you don't plan to use c3os vpn capabilities you can disable the agent entirely - or otherway a cloud-config must be provided with the `c3os` network token.
